%test.quarkus.jacoco.excludes=**/ReflectionConfiguration.class
REST_CONSUMER_APIBASEPATH=restConsumer
REST_CONSUMER_APIPATH=/api-doc
REST_CONSUMER_SERVICEID=restConsumer
REST_CONSUMER_SERVICENAME=/restConsumer
azure.keyvault[0].client-id=${KEYVAULT_CLIENT_ID}
azure.keyvault[0].client-key=${KEYVAULT_CLIENT_KEY}
azure.keyvault[0].enabled=${KEYVAULT_ENABLED:false}
azure.keyvault[0].secret-keys=TODO: put secret keys for this project here
azure.keyvault[0].tenant-id=${KEYVAULT_TENANT_ID}
azure.keyvault[0].uri=${KEYVAULT_URI}
camel.main.globalOptions.CamelLogEipName=app-prueba-extension
camel.main.streamCachingEnabled=true
camel.main.streamCachingSpoolEnabled=true
camel.main.useMdcLogging=true
quarkus.log.category.app-prueba-extension.level=${INTEGRATION_LOG_LEVEL:INFO}
quarkus.log.console.format=%d [%-15.15t] %-5p %-10.10c{1} - %X{camel.exchangeId} - %m%n
quarkus.log.level=INFO
rest.consumer.get-api-base-path=${REST_CONSUMER_APIBASEPATH}
rest.consumer.get-api-path=${REST_CONSUMER_APIPATH}
rest.consumer.get-api-title=${REST_CONSUMER_SERVICEID}
rest.consumer.get-api-version=1.0
rest.consumer.get-service-name=${REST_CONSUMER_SERVICENAME}
